# Generated by Django 5.1.2 on 2024-10-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='John Doe', max_length=100)),
                ('email', models.EmailField(default='johndoe@example.com', max_length=254)),
                ('phone', models.CharField(default='(123) 456-7890', max_length=20)),
                ('cv_file', models.FileField(upload_to='cvs/')),
            ],
        ),
    ]
