# Generated by Django 5.1.2 on 2024-10-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='cv_file',
            field=models.FileField(upload_to='C:\\Users\\maorb\\Desktop\\Work\\Maor Blumberg CV_Updated.pdf'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='email',
            field=models.EmailField(default='maorblumberg@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='cv',
            name='name',
            field=models.CharField(default='Maor Blumberg', max_length=100),
        ),
        migrations.AlterField(
            model_name='cv',
            name='phone',
            field=models.CharField(default='(+972) 54-327073', max_length=20),
        ),
    ]
