# Generated by Django 5.1.2 on 2024-10-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_cv_cv_file_alter_cv_email_alter_cv_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='cv_file',
            field=models.FileField(upload_to='cv_files/'),
        ),
    ]
